# Generated by Django 3.0.6 on 2020-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('quaterly', 'quaterly'), ('half yearly', 'half year'), ('yearly', 'yearly')], max_length=12)),
                ('category', models.CharField(choices=[('BodyBuilding', 'bodybuilding'), ('Fitness', 'Fitness'), ('Weight Lifting', 'Weight Lifting')], max_length=20)),
            ],
        ),
    ]
