# Generated by Django 3.0.6 on 2020-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200517_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('BodyBuilding', 'BodyBuilding'), ('Fitness', 'Fitness'), ('Weight Lifting', 'Weight Lifting'), ('Boxing', 'Boxing')], max_length=20),
        ),
    ]
