# Generated by Django 3.0.6 on 2020-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200519_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(related_name='users', to='core.categorie'),
        ),
    ]
