# Generated by Django 3.0.6 on 2020-05-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200519_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.User'),
        ),
    ]
