# Generated by Django 3.0.6 on 2020-05-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200522_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
