# Generated by Django 3.0.6 on 2020-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200522_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
