# Generated by Django 3.0.6 on 2020-05-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
    ]
