# Generated by Django 3.0.6 on 2020-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('BodyBuilding', 'BodyBuilding'), ('Fitness', 'Fitness'), ('Weight Lifting', 'Weight Lifting')], max_length=20),
        ),
    ]
